[package]
name = "http-replay-proxy"
version = "0.1.0"
edition = "2021"
authors = ["Dorian Maliszewski <maliszewskid3@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version = "4"}
awc = {version = "3.2.0", features = ["rustls-0_21"]}
url = "2.2"
log = "0.4"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
actix-session= {version = "0.8.0", features = ["cookie-session"]}
serde = {version= "1.0", features = ["derive"]}
serde_json = "1.0"
uuid = {version = "1.6.1", features= ["v4"]}
rustls = "0.21"
webpki-roots = "0.25"
tokio = { version = "1.34.0", features = ["full"] }
hyper = { version = "1.0.1", features = ["full"]}
reqwest = { version = "0.11", features = ["json"] }

[[test]]
name = "integration"
path = "tests/tests.rs"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "http-replay-proxy"
